pages:
  czc:
    Intel Core i7-7800X: https://www.czc.cz/intel-core-i7-7800x/217105/produkt
    ASUS GeForce ROG-STRIX-GTX1080TI-11G-GAMING: https://www.czc.cz/asus-geforce-rog-strix-gtx1080ti-11g-gaming-11gb-gddr5x/210368/produkt
  alza:
    Intel Core i7-7800X: https://www.alza.cz/intel-core-i7-7800x-d4977463.htm
    ASUS GeForce ROG-STRIX-GTX1080TI-11G-GAMING: https://www.alza.cz/asus-rog-strix-gaming-geforce-gtx1080ti-11gb-d4828446.htm
