pages:
  czc:
#   tohle je plánovaná pc sestava
    Intel Core i7-7800X: https://www.czc.cz/intel-core-i7-7800x/217105/produkt
    ASUS GeForce ROG-STRIX-GTX1080TI-11G-GAMING: https://www.czc.cz/asus-geforce-rog-strix-gtx1080ti-11g-gaming-11gb-gddr5x/210368/produkt
    ASUS PRIME X299-A - Intel X299: https://www.czc.cz/asus-prime-x299-a-intel-x299/217084/produkt
    ADATA XPG GAMMIX D10 32GB (2x16GB) DDR4 3000: https://www.czc.cz/adata-xpg-gammix-d10-32gb-2x16gb-ddr4-3000-cervena/224077/produkt
    Be quiet! Dark Rock PRO 4: https://www.czc.cz/be-quiet-dark-rock-pro-4/234415/produkt
    Samsung SSD 970 EVO (M.2) - 500GB: https://www.czc.cz/samsung-ssd-970-evo-m-2-500gb/236368/produkt
    Seagate BarraCuda PRO - 4TB: https://www.czc.cz/seagate-barracuda-pro-4tb/217195/produkt
    Seasonic Focus Plus Gold - 850W: https://www.czc.cz/seasonic-focus-plus-gold-850w/220745/produkt
    Fractal Design Meshify C Blackout TG: https://www.czc.cz/fractal-design-meshify-c-blackout-tg-sklo-cerna/220308/produkt
    Arctic Fan F12: https://www.czc.cz/arctic-fan-f12_2/70139/produkt
    Samsung C27HG70: https://www.czc.cz/samsung-c27hg70-led-monitor-27/216838/produkt
#   tohle jsou alternativy
    AMD RYZEN Threadripper 1900X: https://www.czc.cz/amd-ryzen-threadripper-1900x/221634/produkt
    AMD RYZEN Threadripper 1920X: https://www.czc.cz/amd-ryzen-threadripper-1920x/219536/produkt
    AMD RYZEN Threadripper 1950X: https://www.czc.cz/amd-ryzen-threadripper-1950x/219538/produkt
    Intel Core i7-7820X: https://www.czc.cz/intel-core-i7-7820x/217106/produkt
    Intel Core i9-7900X: https://www.czc.cz/intel-core-i9-7900x/217107/produkt
    Intel Core i9-7920X: https://www.czc.cz/intel-core-i9-7920x/222073/produkt
    AMD Ryzen 7 2700: https://www.czc.cz/amd-ryzen-7-2700/233927/produkt
    AMD Ryzen 7 2700X: https://www.czc.cz/amd-ryzen-7-2700x/233928/produkt
    ASUS PRIME X399-A - AMD X399: https://www.czc.cz/asus-prime-x399-a-amd-x399/220307/produkt
    Enermax LiqTech TR4 360: https://www.czc.cz/enermax-liquid-liqtech-tr4-360/228140/produkt
    NOCTUA NH-D15: https://www.czc.cz/noctua-nh-d15/151820/produkt
    ASUS PRIME X470-PRO: https://www.czc.cz/asus-prime-x470-pro-amd-x470/234279/produkt
    Samsung SSD 970 PRO (M.2) - 512GB: https://www.czc.cz/samsung-ssd-970-pro-m-2-512gb/236376/produkt
    MSI GeForce GTX 1080 Ti GAMING X TRIO: https://www.czc.cz/msi-geforce-gtx-1080-ti-gaming-x-trio-11gb-gddr5x/226668/produkt
    EVGA GeForce GTX 1080 Ti FTW3 GAMING: https://www.czc.cz/evga-geforce-gtx-1080-ti-ftw3-gaming-11gb-gddr5x/213737/produkt
    GIGABYTE GeForce AORUS GTX 1080 Ti Xtreme Edition 11G: https://www.czc.cz/gigabyte-geforce-aorus-gtx-1080-ti-xtreme-edition-11g-11gb-gddr5x/212887/produkt
    ASUS GeForce ROG STRIX GAMING GTX1080 DirectCU III: https://www.czc.cz/asus-geforce-rog-strix-gaming-gtx1080-directcu-iii-8gb-gddr5x/192114/produkt
    MSI GeForce GTX 1080 GAMING X 8G: https://www.czc.cz/msi-geforce-gtx-1080-gaming-x-8g-8gb-gddr5x/192164/produkt
    EVGA GeForce GTX 1080 FTW2 GAMING iCX: https://www.czc.cz/evga-geforce-gtx-1080-ftw2-gaming-icx-8gb-gddr5x/208749/produkt
    GIGABYTE GeForce GTX 1080 G1 Gaming: https://www.czc.cz/gigabyte-geforce-gtx-1080-g1-gaming-8gb-gddr5x/192244/produkt
    ASUS GeForce ROG-STRIX-GTX1070TI-A8G-GAMING: https://www.czc.cz/asus-geforce-rog-strix-gtx1070ti-a8g-gaming-8gb-gddr5/225117/produkt
    MSI GeForce GTX 1070 Ti GAMING 8G: https://www.czc.cz/msi-geforce-gtx-1070-ti-gaming-8g-8gb-gddr5/225169/produkt
    EVGA GeForce GTX 1070 Ti SC Gaming: https://www.czc.cz/evga-geforce-gtx-1070-ti-sc-gaming-8gb-gddr5/235586/produkt
    GIGABYTE GeForce AORUS GTX 1070 Ti 8G: https://www.czc.cz/gigabyte-geforce-aorus-gtx-1070-ti-8g-8gb-gddr5/229092/produkt
    ASUS GeForce ROG STRIX GAMING GTX1070 DirectCU III: https://www.czc.cz/asus-geforce-rog-strix-gaming-gtx1070-directcu-iii-8gb-gddr5/193226/produkt
    MSI GeForce GTX 1070 GAMING X 8G: https://www.czc.cz/msi-geforce-gtx-1070-gaming-x-8g-8gb-gddr5/192504/produkt
    EVGA GeForce GTX 1070 FTW2 GAMING iCX: https://www.czc.cz/evga-geforce-gtx-1070-ftw2-gaming-icx-8gb-gddr5/208751/produkt
    GIGABYTE GeForce GTX 1070 G1 Gaming: https://www.czc.cz/gigabyte-geforce-gtx-1070-g1-gaming-8gb-gddr5/192961/produkt
    ASUS GeForce GTX 1060 ROG STRIX-GTX1060-6G-GAMING: https://www.czc.cz/asus-geforce-gtx-1060-rog-strix-gtx1060-6g-gaming-6gb-gddr5/195125/produkt
    MSI GeForce GTX 1060 GAMING X 6G: https://www.czc.cz/msi-geforce-gtx-1060-gaming-x-6g-6gb-gddr5/194879/produkt
    EVGA GeForce GTX 1060 FTW GAMING: https://www.czc.cz/evga-geforce-gtx-1060-ftw-gaming-6gb-gddr5/216883/produkt
    GIGABYTE GeForce GTX 1060 GAMING-6GD: https://www.czc.cz/gigabyte-geforce-gtx-1060-gaming-6gd-6gb-gddr5/195148/produkt
  alza:
    Intel Core i7-7800X: https://www.alza.cz/intel-core-i7-7800x-d4977463.htm
    ASUS GeForce ROG-STRIX-GTX1080TI-11G-GAMING: https://www.alza.cz/asus-rog-strix-gaming-geforce-gtx1080ti-11gb-d4828446.htm
    ASUS PRIME X299-A - Intel X299: https://www.alza.cz/asus-prime-x299-a-d5007825.htm
    ADATA XPG GAMMIX D10 32GB (2x16GB) DDR4 3000: https://www.alza.cz/adata-32gb-ddr4-3000mhz-cl16-xpg-gammix-d10-cervena-d5118748.htm
    Be quiet! Dark Rock PRO 4: https://www.alza.cz/be-quiet-dark-rock-pro-4-d5340955.htm
    Samsung SSD 970 EVO (M.2) - 500GB: https://www.alza.cz/samsung-970-evo-500gb-d5319054.htm
    Seagate BarraCuda PRO - 4TB: https://www.alza.cz/seagate-barracuda-pro-4tb-d5147619.htm
    Seasonic Focus Plus Gold - 850W: https://www.alza.cz/seasonic-focus-plus-850-gold-d5041957.htm
    Fractal Design Meshify C Blackout TG: https://www.alza.cz/fractal-design-define-meshify-c-blackout-tg-d5090782.htm
    Arctic Fan F12: https://www.alza.cz/arctic-f12-120mm-d349024.htm
    Samsung C27HG70: https://www.alza.cz/27-samsung-c27hg70-d5088174.htm

    AMD RYZEN Threadripper 1900X: https://www.alza.cz/amd-ryzen-threadripper-1900x-d5100403.htm
    AMD RYZEN Threadripper 1920X: https://www.alza.cz/amd-ryzen-threadripper-1920x-d5073885.htm
    AMD RYZEN Threadripper 1950X: https://www.alza.cz/amd-ryzen-threadripper-1950x-d5073886.htm
    Intel Core i7-7820X: https://www.alza.cz/intel-core-i7-7820x-d4977502.htm
    Intel Core i9-7900X: https://www.alza.cz/intel-core-i9-7900x-d4977501.htm
    Intel Core i9-7920X: https://www.alza.cz/intel-core-i9-7920x-d5069924.htm
    AMD Ryzen 7 2700: https://www.alza.cz/amd-ryzen-7-2700-d5287887.htm
    AMD Ryzen 7 2700X: https://www.alza.cz/amd-ryzen-7-2700x-d5287906.htm
    ASUS PRIME X399-A - AMD X399: https://www.alza.cz/asus-prime-x399-a-d5092237.htm
    Enermax LiqTech TR4 360: https://www.alza.cz/enermax-liqtech-tr4-360-d5158441.htm
    NOCTUA NH-D15: https://www.alza.cz/noctua-nh-d15-d1480167.htm
    ASUS PRIME X470-PRO: https://www.alza.cz/asus-prime-x470-pro-d5303004.htm
    Samsung SSD 970 PRO (M.2) - 512GB: https://www.alza.cz/samsung-970-pro-512gb-d5319059.htm
    MSI GeForce GTX 1080 Ti GAMING X TRIO: https://www.alza.cz/msi-geforce-gtx-1080ti-gaming-x-trio-d5149603.htm
    EVGA GeForce GTX 1080 Ti FTW3 GAMING: https://www.alza.cz/evga-geforce-gtx-1080-ti-ftw3-hybrid-gaming-d5227719.htm
    GIGABYTE GeForce AORUS GTX 1080 Ti Xtreme Edition 11G: https://www.alza.cz/gigabyte-geforce-aorus-gtx-1080-ti-xtreme-edition-11g
    ASUS GeForce ROG STRIX GAMING GTX1080 DirectCU III: https://www.alza.cz/asus-rog-strix-gaming-gtx1080-advanced-edition-directcu-iii-8gb-d4395854.htm
    MSI GeForce GTX 1080 GAMING X 8G: https://www.alza.cz/msi-gtx-1080-gaming-x-8g-d4290774.htm
    EVGA GeForce GTX 1080 FTW2 GAMING iCX: https://www.alza.cz/evga-geforce-gtx-1080-ftw2-gaming-icx-d4761351.htm
    GIGABYTE GeForce GTX 1080 G1 Gaming: https://www.alza.cz/gigabyte-geforce-gtx-1080-g1-gaming-d4291323.htm
    ASUS GeForce ROG-STRIX-GTX1070TI-A8G-GAMING: https://www.alza.cz/asus-rog-strix-gaming-geforce-gtx-1070ti-advanced-edition-directcu-iii-8gb-d5147076.htm
    MSI GeForce GTX 1070 Ti GAMING 8G: https://www.alza.cz/msi-geforce-gtx-1070-ti-gaming-8g-d5147068.htm
    EVGA GeForce GTX 1070 Ti SC Gaming: https://www.alza.cz/evga-geforce-gtx-1070-ti-sc-gaming-acx-3-0-levne-d5219238.htm
    GIGABYTE GeForce AORUS GTX 1070 Ti 8G: https://www.alza.cz/gigabyte-geforce-aorus-gtx-1070-ti-d5265929.htm
    ASUS GeForce ROG STRIX GAMING GTX1070 DirectCU III: https://www.alza.cz/asus-rog-strix-gaming-gtx1070-directcu-iii-8gb-d4329420.htm
    MSI GeForce GTX 1070 GAMING X 8G: https://www.alza.cz/msi-gtx-1070-gaming-x-8g-d4305009.htm
    EVGA GeForce GTX 1070 FTW2 GAMING iCX: https://www.alza.cz/evga-geforce-gtx-1070-ftw2-gaming-icx-d4788138.htm
    GIGABYTE GeForce GTX 1070 G1 Gaming: https://www.alza.cz/gigabyte-geforce-gtx-1070-g1-gaming-d4300277.htm
    ASUS GeForce GTX 1060 ROG STRIX-GTX1060-6G-GAMING: https://www.alza.cz/asus-strix-gaming-gtx1060-6gb-d4373222.htm
    MSI GeForce GTX 1060 GAMING X 6G: https://www.alza.cz/msi-gtx-1060-gaming-x-6g-d4367058.htm
    EVGA GeForce GTX 1060 FTW GAMING: https://www.alza.cz/evga-geforce-gtx-1060-ftw-d4373384.htm
    GIGABYTE GeForce GTX 1060 GAMING-6GD: https://www.alza.cz/gigabyte-geforce-gtx-1060-g1-gaming-d4371532.htm